### ISSUE TITLE
solver.py代码是不是有一些问题呢？

### ISSUE THREAD

**Issue by wosyoo** [PecholaL/MAIN-VC#4]
<img width="564" alt="微信图片_20240607165930" src="https://github.com/PecholaL/MAIN-VC/assets/83287534/6f125c86-bfde-4e3b-8bbe-ea370f12a4e9">
<img width="409" alt="微信图片_20240607170036" src="https://github.com/PecholaL/MAIN-VC/assets/83287534/328bf96e-19c6-4ec0-be2d-a7316f6de1f0">
mainvc_step只传了一个data参数，emb_不知道从哪里计算来的。

**Comment by PecholaL** [comment]
是的，目前版本的代码会存在一些错误。因为最终代码在公司服务器上调试和运行，但由于安全规定服务器上代码无法导出。后续将与最终版比对。现已修正指出的错误，谢谢。

**Comment by wosyoo** [comment]
感谢回复！
